const queries = new URLSearchParams(window.location.search);
var ip = queries.get('ip'); 
var browser = queries.get('browser');
var canary = queries.get('canary');
var fs = queries.get('fs');
var resolution = queries.get('resolution');
var chromium = queries.get('chromium');
var tor = queries.get('tor')
var mobile = queries.get('mobile');
var platform = queries.get('platform');
var os = queries.get('os');
var utc = queries.get('utc');
var language = queries.get('language');
var ws = queries.get('ws');
var version = queries.get('version');
var gpuInfo = queries.get('gpuinfo');
var url = queries.get('url');
var protocol = queries.get('protocol');
var cpus = queries.get('cpus');
var vendor = queries.get('vendor');
var cookies = queries.get('cookies');
var referrer = queries.get('referrer');
var color = queries.get('color');
var darkmode = queries.get('darkmode');
var timezone = queries.get('timezone');
var orientation = queries.get('orientation');
var java = queries.get('java');
var gpuVendor = queries.get('gpuvendor');
var adb = queries.get('adb');
var html5 = queries.get('html5');
var doNotTrack = queries.get('donottrack');
var date = queries.get('date');
var cookie = queries.get('cookie');
var vb = queries.get('vb');
var ram = queries.get('ram');
var adb = queries.get('adb');
var darkMode = queries.get('darkMode')
var arch = queries.get('arch')
var cookie = queries.get('cookie')



const darkModeTag = document.getElementById('darkmode')
const ipTag = document.getElementById('ip');
const browserTag = document.getElementById('browser');
const canaryTag = document.getElementById('canary');
const fsTag = document.getElementById('fs');
const resTag = document.getElementById('resolution');
const chromiumTag = document.getElementById('chromium');
const torTag = document.getElementById('tor');
const mobileTag = document.getElementById('mobile');
const platformTag = document.getElementById('platform');
const utcTag = document.getElementById('utc');
const languageTag = document.getElementById('language');
const wsTag = document.getElementById('ws');
const versionTag = document.getElementById('version');
const gpuInfoTag = document.getElementById('gpuInfo');
const urlTag = document.getElementById('url');
const protocolTag = document.getElementById('protocol');
const cpusTag = document.getElementById('cpus');
const vendorTag = document.getElementById('vendor');
const cookiesTag = document.getElementById('cookies');
const referrerTag = document.getElementById('referrer');
const colorTag = document.getElementById('color');
const timezoneTag = document.getElementById('timezone');
const orientationTag = document.getElementById('orientation');
const javaTag = document.getElementById('java');
const gpuVendorTag = document.getElementById('gpuvendor');
const adbTag = document.getElementById('adb');
const html5Tag = document.getElementById('html5');
const doNotTrackTag = document.getElementById('donottrack');
const dateTag = document.getElementById('date');
const cookieTag = document.getElementById('cookie');
const ramTag = document.getElementById('ram');
const vivaldiorbrave = document.getElementById('or');
const osTag = document.getElementById('os');
const archTag = document.getElementById('arch');


vivaldiorbrave.innerText = vb;
ipTag.innerText = ip;
browserTag.innerText = browser;
canaryTag.innerText = canary;
fsTag.innerText = fs;
resTag.innerText = resolution;
chromiumTag.innerText = chromium;
torTag.innerText = tor;
mobileTag.innerText = mobile;
platformTag.innerText = platform;
utcTag.innerText = utc;
languageTag.innerText = language;
wsTag.innerText = ws;
versionTag.innerText = version;
gpuInfoTag.setAttribute('href','javascript:alert(gpuInfo);');
urlTag.setAttribute('href',url)
protocolTag.innerText = protocol;
cpusTag.innerText = cpus;
// vendorTag.innerText = vendor;
osTag.innerText = os;
cookiesTag.innerText = cookies;
referrerTag.innerText = referrer;
colorTag.innerText = color;
darkModeTag.innerText = darkMode;   
timezoneTag.innerText = timezone;
orientationTag.innerText = orientation;
javaTag.innerText = java;
gpuVendorTag.innerText = gpuVendor;
adbTag.innerText = "false";
html5Tag.innerText = html5;
doNotTrackTag.innerText = doNotTrack;
dateTag.innerText = date;
cookieTag.innerText = cookie;
ramTag.innerText = ram;
archTag.innerText = arch;
darkModeTag.innerText = darkmode;
cookieTag.innerText = cookie;
//
var URLobj = new URL(url);
const link = URLobj.host + URLobj.pathname;
urlTag.innerText = link;
//
